### ISSUE TITLE
Build Server

### ISSUE THREAD

**Issue by mattridgway** [smudge202/clean-living#5]
We should setup a build server, for... well.. building.

AppVeyor seems a good a choice as any considering this is an open source project, unless there are any objections?

At the point it becomes appropriate we can publish to a NuGet feed, but I don't think that needs to be setup yet.

**Comment by smudge202** [comment]
Setup CI ++
AppVeyor ++

Agreed, no need for nuget (or any deployment) yet.

**Comment by mattridgway** [comment]
thoughts on tagging branches? successful builds only? "build-x.x.x.x"

**Comment by smudge202** [comment]
I'd say no tagging right now. Perhaps in the future we'll tag the nuget deployments with beta when appropriate, but until we're in a position to publish anything, they don't mean much.

CI without the tags still useful of course.

**Comment by herecydev** [comment]
Yer I think tagging isn't such a big deal, considering the effort you put in to make the other project work perfectly.

I think focus should be on producing this engine, fine tuning those things can come later.

**Comment by smudge202** [comment]
Because you just can't get the staff nowadays! ;) :)

``` yaml
version: 0.0.1.{build}
os: Visual Studio 2015 CTP 6
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
before_build:
- nuget restore
build:
  verbosity: normal
notifications:
- provider: Email
  to:
  - clean.living.devs@gmail.com
  subject: AppVeyor Build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
```

[![Build status](https://ci.appveyor.com/api/projects/status/2wwrvmewlqjrdvkq?svg=true)](https://ci.appveyor.com/project/Smudge202/clean-living)

(Build success at time of writing)
